### ISSUE TITLE
Should tests for `@embed`: `@last` be restricted to JSON-LD 1.0?

### ISSUE THREAD

**Issue by kal** [w3c/json-ld-framing#110]
The test t0059 tests handling of `@last` as a value of `@embed` with a specVersion of 1.1, but the 1.1 spec says that this is an invalid `@embed` value. Should the `specVersion` option for this test be `json-ld-1.0` rather than 1.1?

**Comment by gkellogg** [comment]
It is supported as processingMode is set to json-ld-1.0. Even though framing was not a 1.0 recommendation, but a community spec, it was widely implemented, and `@last` was, in fact, the default value in the previous version.

As other places in the spec mention things to do for json-ld-1.0 processing mode, it might be worth a future editorial update to add these things, but it would mean placing emphasis on some specifically outdated mechanisms.

**Comment by kal** [comment]
Thanks Greg. I agree that an editorial update would be very useful. If the intention is that a JSON-LD 1.1 Framing conformant processor should implement support for `@first` and `@last` then those values and the intended semantics that should ideally be included in the specification, and at a minimum the definition for the allowed values of `@embed` should include those values and note that support for them is expected.

**Comment by gkellogg** [comment]
It should also probably be clear that operating in json-ld-1.0 mode is not required for conformance. It's intended for backwards compatibility.

**Comment by gkellogg** [comment]
Removing the ErratumRaised flag, as this does not affect the specification, itself.
