### ISSUE TITLE
Can frames produce id maps?

### ISSUE THREAD

**Issue by rybesh** [w3c/json-ld-framing#119]
I would like to use framing to produce an [id map](https://www.w3.org/TR/json-ld/#id-maps), but this does not seem to work very well with the JSON-LD processors I’ve tried.

Take for example the following graph:

```jsonld
{
  "@graph": [
    {
      "@id": "http://n2t.net/ark:/39333/ncg/dataset",
      "@type": "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag",
      "member": [
        "http://n2t.net/ark:/39333/ncg/place/NCG11248",
        "http://n2t.net/ark:/39333/ncg/place/NCG07554",
        "http://n2t.net/ark:/39333/ncg/place/NCG03755"
      ]
    },
    {
      "@id": "http://n2t.net/ark:/39333/ncg/place/NCG03755",
      "@type": "http://n2t.net/ark:/39333/ncg/type#Mountain",
      "county": "http://n2t.net/ark:/39333/ncg/place/NCG11248",
      "label": "Crawford Mountain"
    },
    {
      "@id": "http://n2t.net/ark:/39333/ncg/place/NCG07554",
      "@type": "http://n2t.net/ark:/39333/ncg/type#Community",
      "county": "http://n2t.net/ark:/39333/ncg/place/NCG11248",
      "label": "Ichley"
    },
    {
      "@id": "http://n2t.net/ark:/39333/ncg/place/NCG11248",
      "@type": "http://n2t.net/ark:/39333/ncg/type#County",
      "label": "Orange County",
      "description": "Not to be confused with Orange County, CA"
    }
  ],
  "@context": {
    "label": {
      "@id": "http://www.w3.org/2004/02/skos/core#label"
    },
    "description": {
      "@id": "http://www.w3.org/2004/02/skos/core#note"
    },
    "county": {
      "@id": "http://n2t.net/ark:/39333/ncg/vocab#county",
      "@type": "@id"
    },
    "member": {
      "@id": "http://www.w3.org/2000/01/rdf-schema#member",
      "@type": "@id"
    }
  }
}
```

And this frame:

```jsonld
{
  "@context": {
    "@base": "http://n2t.net/ark:/39333/ncg/place/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "ncv": "http://n2t.net/ark:/39333/ncg/vocab#",
    "nct": "http://n2t.net/ark:/39333/ncg/type#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "records": {
      "@container": "@set",
      "@type": "@id",
      "@id": "rdfs:member"
    },
    "county": {
      "@container": "@set",
      "@type": "@id",
      "@id": "ncv:county"
    }
  },
  "@type": "rdf:Bag",
  "records": {
    "@id": {},
    "county": {
      "@embed": "@always",
      "@explicit": true,
      "skos:label": {}
    }
  }
}
```

Which produces:

```jsonld
{
  "@context": {
    "@base": "http://n2t.net/ark:/39333/ncg/place/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "ncv": "http://n2t.net/ark:/39333/ncg/vocab#",
    "nct": "http://n2t.net/ark:/39333/ncg/type#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "records": {
      "@container": "@set",
      "@type": "@id",
      "@id": "rdfs:member"
    },
    "county": {
      "@container": "@set",
      "@type": "@id",
      "@id": "ncv:county"
    }
  },
  "@id": "../dataset",
  "@type": "rdf:Bag",
  "records": [
    {
      "@id": "NCG11248",
      "@type": "nct:County",
      "county": [],
      "skos:label": "Orange County",
      "skos:note": "Not to be confused with Orange County, CA"
    },
    {
      "@id": "NCG07554",
      "@type": "nct:Community",
      "county": [
        {
          "@id": "NCG11248",
          "@type": "nct:County",
          "skos:label": "Orange County"
        }
      ],
      "skos:label": "Ichley"
    },
    {
      "@id": "NCG03755",
      "@type": "nct:Mountain",
      "county": [
        {
          "@id": "NCG11248",
          "@type": "nct:County",
          "skos:label": "Orange County"
        }
      ],
      "skos:label": "Crawford Mountain"
    }
  ]
}
```

(See the above on the [playground](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fdataset%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23Bag%22%2C%22member%22%3A%5B%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG07554%22%2C%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG03755%22%5D%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG03755%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23Mountain%22%2C%22county%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22label%22%3A%22Crawford%20Mountain%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG07554%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23Community%22%2C%22county%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22label%22%3A%22Ichley%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23County%22%2C%22label%22%3A%22Orange%20County%22%2C%22description%22%3A%22Not%20to%20be%20confused%20with%20Orange%20County%2C%20CA%22%7D%5D%2C%22%40context%22%3A%7B%22label%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23label%22%7D%2C%22description%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23note%22%7D%2C%22county%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fvocab%23county%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22member%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23member%22%2C%22%40type%22%3A%22%40id%22%7D%7D%7D&frame=%7B%22%40context%22%3A%7B%22%40base%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2F%22%2C%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%2C%22rdfs%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%22%2C%22ncv%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fvocab%23%22%2C%22nct%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23%22%2C%22skos%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%22%2C%22records%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22rdfs%3Amember%22%7D%2C%22county%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22ncv%3Acounty%22%7D%7D%2C%22%40type%22%3A%22rdf%3ABag%22%2C%22records%22%3A%7B%22%40id%22%3A%7B%7D%2C%22county%22%3A%7B%22%40embed%22%3A%22%40always%22%2C%22%40explicit%22%3Atrue%2C%22skos%3Alabel%22%3A%7B%7D%7D%7D%7D)).

So far so good.

Now, I would like to change the `records` container from a `@set` to an `@id` map. But when I [do that](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fdataset%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23Bag%22%2C%22member%22%3A%5B%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG07554%22%2C%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG03755%22%5D%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG03755%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23Mountain%22%2C%22county%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22label%22%3A%22Crawford%20Mountain%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG07554%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23Community%22%2C%22county%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22label%22%3A%22Ichley%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23County%22%2C%22label%22%3A%22Orange%20County%22%2C%22description%22%3A%22Not%20to%20be%20confused%20with%20Orange%20County%2C%20CA%22%7D%5D%2C%22%40context%22%3A%7B%22label%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23label%22%7D%2C%22description%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23note%22%7D%2C%22county%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fvocab%23county%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22member%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23member%22%2C%22%40type%22%3A%22%40id%22%7D%7D%7D&frame=%7B%22%40context%22%3A%7B%22%40base%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2F%22%2C%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%2C%22rdfs%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%22%2C%22ncv%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fvocab%23%22%2C%22nct%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23%22%2C%22skos%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%22%2C%22records%22%3A%7B%22%40container%22%3A%22%40id%22%2C%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22rdfs%3Amember%22%7D%2C%22county%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22ncv%3Acounty%22%7D%7D%2C%22%40type%22%3A%22rdf%3ABag%22%2C%22records%22%3A%7B%22%40id%22%3A%7B%7D%2C%22county%22%3A%7B%22%40embed%22%3A%22%40always%22%2C%22%40explicit%22%3Atrue%2C%22skos%3Alabel%22%3A%7B%7D%7D%7D%7D) I get the error `jsonld.SyntaxError: Invalid JSON-LD syntax; a JSON-LD frame must be a single object.` (I’m not sure what that error means, since the frame is still a single object.)

Should this work? I can’t find any mention of id maps in the framing spec. Some simpler examples seem to work, but I can’t get anything to work that involves specifying anything (property matches or processing directives) below the level of the id map.

**Comment by gkellogg** [comment]
What's happening is that when you define "records" with `"@container": "@id"`, the frame looks like the object value should be an ID map, but it isn't Wrap the value in an array.

Recall that ID maps are an attribute of compaction, not framing, but as you've found, when used in a frame it may require you to conform to the shape required.

This is the frame I used:
```json
{
  "@context": {
    "@base": "http://n2t.net/ark:/39333/ncg/place/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "ncv": "http://n2t.net/ark:/39333/ncg/vocab#",
    "nct": "http://n2t.net/ark:/39333/ncg/type#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "records": {
      "@container": "@id",
      "@type": "@id",
      "@id": "rdfs:member"
    },
    "county": {
      "@container": "@set",
      "@type": "@id",
      "@id": "ncv:county"
    }
  },
  "@type": "rdf:Bag",
  "records": [{
    "@id": {},
    "county": {
      "@embed": "@always",
      "@explicit": true,
      "skos:label": {}
    }
  }]
}
```

And, you can load it in the playground [here](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fdataset%22%2C%22%40type%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23Bag%22%2C%22member%22%3A%5B%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG07554%22%2C%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG03755%22%5D%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG03755%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23Mountain%22%2C%22county%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22label%22%3A%22Crawford%20Mountain%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG07554%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23Community%22%2C%22county%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22label%22%3A%22Ichley%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2FNCG11248%22%2C%22%40type%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23County%22%2C%22label%22%3A%22Orange%20County%22%2C%22description%22%3A%22Not%20to%20be%20confused%20with%20Orange%20County%2C%20CA%22%7D%5D%2C%22%40context%22%3A%7B%22label%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23label%22%7D%2C%22description%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23note%22%7D%2C%22county%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fvocab%23county%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22member%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23member%22%2C%22%40type%22%3A%22%40id%22%7D%7D%7D&frame=%7B%22%40context%22%3A%7B%22%40base%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fplace%2F%22%2C%22rdf%22%3A%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%22%2C%22rdfs%22%3A%22http%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%22%2C%22ncv%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Fvocab%23%22%2C%22nct%22%3A%22http%3A%2F%2Fn2t.net%2Fark%3A%2F39333%2Fncg%2Ftype%23%22%2C%22skos%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%22%2C%22records%22%3A%7B%22%40container%22%3A%22%40id%22%2C%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22rdfs%3Amember%22%7D%2C%22county%22%3A%7B%22%40container%22%3A%22%40set%22%2C%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22ncv%3Acounty%22%7D%7D%2C%22%40type%22%3A%22rdf%3ABag%22%2C%22records%22%3A%5B%7B%22%40id%22%3A%7B%7D%2C%22county%22%3A%7B%22%40embed%22%3A%22%40always%22%2C%22%40explicit%22%3Atrue%2C%22skos%3Alabel%22%3A%7B%7D%7D%7D%5D%7D).

**Comment by rybesh** [comment]
Perfect, thank you!
