### ISSUE TITLE
Possible typos

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/json-ld-framing#121]
Hello from Tokyo.

I am translating the "JSON-LD 1.1 Framing" specification into Japanese now.
Thank you for the great specification!

I found some possible typos:

Sec. 5.1, "14.9)" might be unnecessary.
Sec. 5.2, "and" might be missing before "the JSON-LD 1.1 API".
Sec. D and E, a period might be missing after "defaulting to false".

Best regards,
KAMITSUNA Shuji,

**Comment by shujikamitsuna** [comment]
Let me point out one more possible typo.
Sec. 5.1, "add en entry" might be "add an entry".

And I found a missing link (a link to "Commit history"):
https://github.com/w3c/json-ld-framing/commits/master

Thank you.

**Comment by gkellogg** [comment]
> Hello from Tokyo.
> 
> I am translating the "JSON-LD 1.1 Framing" specification into Japanese now.
> Thank you for the great specification!
> 
> I found some possible typos:
> 
> Sec. 5.1, "14.9)" might be unnecessary.

:+1:

> Sec. 5.2, "and" might be missing before "the JSON-LD 1.1 API".

:+1:

This can be simplified.

> Sec. D and E, a period might be missing after "defaulting to false".

:+1:

> Sec. 5.1, "add en entry" might be "add an entry".

:+1:

> And I found a missing link (a link to "Commit history"):
> https://github.com/w3c/json-ld-framing/commits/master

I don't see this. It is automatically generated by ReSpec, and the repo configuration references the "main" branch.
