### ISSUE TITLE
"Framing" is an unfortunate choice of verb

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/json-ld-framing#13]
In reviewing the 1.1 spec I was surprised to discover that "framing" is not the process of surrounding JSON-LD data with a "frame". In my experience this is the most common definition of framing in a technical context.

i.e. Using special delimiters or length prefixes around a chunk of data that "frames" that data and differentiates one chunk from another when streamed between processes.

This is the definition I am accustomed to and I wonder if I am alone in being surprised that JSON-LD framing appears to be used to define a structure as opposed to a frame.

**Comment by gkellogg** [comment]
@dlongley is there a paragraph we could add to the introduction that would motivate the use of the term "framing" to describe this process?

**Comment by dlongley** [comment]
Maybe something along these lines:

> Using delimiters around a chunk of data is known as "framing". JSON-LD uses JSON delimiters such as `{` and `}` to separate statements about a particular subject. JSON-LD also allows subjects to reference other subjects through the use of their identifiers, expressed as strings.
> 
> However, given that JSON-LD represents a graph of information, there is more than one way to frame the statements about several related subjects into a whole document. In fact, a graph of information can be thought of as a long list of independent statements (aka "triples" or "quads") that are not bundled together in any way.
> 
> The JSON-LD Framing API enables a developer to specify exactly how they would like data to be framed, such that statements about a particular subject are bundled together, delimited via `{` and `}`, and such that the subjects they relate to "nest" into a particular tree structure that matches what their application expects.

**Comment by gkellogg** [comment]
Excellent text, Dave, thanks!

**Comment by azaroth42** [comment]
Thanks @dlongley, @gkellogg. 

Per the WG [resolution](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-09-21-json-ld#resolution2), we cannot change the name at this stage, but can add text explaining why that name was chosen.  This issue can thus be closed when #17 is merged.
