### ISSUE TITLE
IANA profile should be `frame` not `framed`

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/json-ld-framing#132]
https://www.w3.org/TR/json-ld11-framing/#iana-considerations:
> http://www.w3.org/ns/json-ld#framed
To specify a JSON-LD [Frame](https://www.w3.org/TR/json-ld11-framing/#dfn-frame).
The http://www.w3.org/ns/json-ld#framed SHOULD be used when serving and requesting a JSON-LD frame document.

https://w3c.github.io/json-ld-syntax/#application-ld-json
> This specification defines six values for the profile parameter.
http://www.w3.org/ns/json-ld#frame
To request or specify a [JSON-LD frame document](https://www.w3.org/TR/json-ld11-framing/#dfn-frame).
http://www.w3.org/ns/json-ld#framed
To request or specify [framed JSON-LD document form](https://w3c.github.io/json-ld-syntax/#dfn-framed-document-form).

- I think that in json-ld11-framing, the correct profile to use is `frame` not `framed`

**Comment by gkellogg** [comment]
Thanks for noticing this. I don't recall right now why we had a separate IANA considerations section in the Framing document, as it is redundant with that from the Syntax document, and as you point out, inconsistent.

I think the corrective action is the just make the Framing document consistent with the Syntax document for this particular profile parameter in an Erratum.

**Comment by gkellogg** [comment]
Summary: Update IANA considerations to make the`http://www.w3.org/ns/json-ld#frame` parameter required and change from `http://www.w3.org/ns/json-ld#frame`, which was inaccurate and inconsistent with the same definition in the with the narrative text and with the same definition in [JSON-LD11](https://www.w3.org/TR/json-ld11/#iana-considerations).

**Comment by gkellogg** [comment]
I'm re-opening this to undo the normative change to the ReSpec source to allow for future publication without going through the CR cycle again.

**Comment by gkellogg** [comment]
The lines noted in #137  should be added back when ready for a new CR phase.

**Comment by VladimirAlexiev** [comment]
hi @gkellogg I'm closing this based on your latest commit. Please reopen if I'm wrong
