### ISSUE TITLE
spec subtitle wrong?

### ISSUE THREAD

**Issue by dret** [w3c/json-ld-framing#14]
the FPWD at https://www.w3.org/TR/2018/WD-json-ld11-framing-20180911/ has the subtitle "An Application Programming Interface for the JSON-LD Syntax". is it possible that this subtitle was intended for the JSON-LD 1.1 API spec instead?

**Comment by gkellogg** [comment]
It is part of the JSON-LD API, but yes, that could be more clear.

**Comment by gkellogg** [comment]
Perhaps "An Extension to the Application Programming Interface for the JSON-LD Syntax".

**Comment by dret** [comment]
On Sep 21, 2018, at 09:13, Gregg Kellogg <notifications@github.com> wrote:
> Perhaps "An Extension to the Application Programming Interface for the JSON-LD Syntax".
> 

sounds good to me!
