### ISSUE TITLE
(Editorial) visually separate the different examples?

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-framing#35]
At the moment, the document uses example boxes for the frames, the raw JSON-LD, and the processed/shaped JSON-LD. Because they are all JSON-LD, it is difficult for first time readers to easily distinguish among these three different roles. It would be very helpful, IMHO, if we used three different styles (probably the simplest is to use a different background colors) for the three cases.

**Comment by gkellogg** [comment]
See example styling added to #42.
