### ISSUE TITLE
(Mostly) Editorial issues Part I

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-framing#36]
- [x] I think adding the same choice of example syntaxes as in the syntax document would be good (for the framing results).
- [x] 2.3.1. It is a bit unclear why one has to use the value of `"@last"` and `"@never"` rather than using boolean values. Those two terms do not look very intuitive for me... 
- [x] 2.3.2, first paragraph: for the purpose of readability I would switch the last two sentences.
- [x] Last sentence of 2.3.2: "fram" -> "frame"
- [x] An example for the omit default flag should be added to to 2.3.3.

**Comment by gkellogg** [comment]
> * I think adding the same choice of example syntaxes as in the syntax document would be good (for the framing results).

I didn't think it always made sense; you have an example with a source document, an example with the frame, and an example with the result, which are all related internally so they can be verified. We _could_ provide both an expanded and compacted version of the source document, but as the entire point of the document is how to create the syntactic framed result, showing expanded, TriG, and tabular versions of this is not germane to the use cases being described. The only reason to do this is so that examples look the same in syntax and framing docs (and API), but it won't be useful in helping people to understand the point of framing.

**Comment by iherman** [comment]
Maybe you are right. Personally, I still 'see' things better in Turtle, but that may only be me.

**Comment by gkellogg** [comment]
> * 2.3.1. It is a bit unclear why one has to use the value of `"@last"` and `"@never"` rather than using boolean values. Those two terms do not look very intuitive for me...

At one time, `@embed` was simply boolean valued, but as more was taken on, the value space evolved to include `@always`, `@last` (synonym for `true`), and `@never` (synonym for `false`). Arguably, the boolean values should be deprecated/removed, if anything. These are described in [4.1](https://w3c.github.io/json-ld-framing/#framing-keywords).

* `@always`, as it says, always embeds values, even if it leads to duplication,
* `@last` ensure that a value is embedded, but does not do duplication, and
* `@never` ensures that values are never embedded, although they may be included in a different part of the JSON tree as expanded.

**Comment by iherman** [comment]
Ouch. I got caught on one thing: I did _not_ go into the details yet for the terminology, where `@always` is mentioned. However, in the informal description of framing, i.e., section 2, `@always` _is not even mentioned_, let alone there is no example.

I agree that if it is a three-way option then boolean is not appropriate.

**Comment by dlongley** [comment]
There also is a fourth option implemented in jsonld.js: `@link` (which does in-memory links for embeds). I can't remember why we dropped support for this in the spec; I searched around and didn't see anything.

**Comment by gkellogg** [comment]
We dropped it, as the result of `@link` can’t be expressed in JSON. There was a discussion for another spec that might do this to represent in-memory results or some other format that could represent graphs with cycles.

**Comment by dlongley** [comment]
@gkellogg, Ok, thanks.

**Comment by azaroth42** [comment]
:+1: to deprecating the booleans (though we shouldn't remove them)

**Comment by gkellogg** [comment]
For the omit default flag, I raised issue #41.

**Comment by gkellogg** [comment]
@azaroth42 the booleans look odd next to keywords, and as this has never been published, I don't think our spec needs to mention them, but my implementation (and I expect @dlongley's) will support them indefinitely.

**Comment by gkellogg** [comment]
@dlongley I added an `@omitDefault` example which works, but doesn't really illustrate why you might want to use it. (I don't really understand myself). Perhaps you can improve it?

**Comment by gkellogg** [comment]
Closed via #42.
