### ISSUE TITLE
Keywords for options

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-framing#37]
Why isn't there a keyword for all options systematically?  There is `@embed`, `@explicit` (although I am not sure its choice is the best, but that is bike shedding), but there isn't any `@omit-default`, `@omit-graph`, `@require-all`.
    
I _think_ the reason may be that if, say, `requireAll` is an API flag, then it is global and not per frame. However, if that is the reason, the question becomes: why can't those flags be frame specific?

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-02-22-json-ld.html#section3-1).

- `RESOLVED:  Keep #37 open for @omit-graph`
<details><summary><i class="differentiate">View the transcript</i></summary>
3.1. Keywords for options<br/>
Simon Steyskal: <a href="https://github.com/w3c/json-ld-framing/issues/37">https://github.com/w3c/json-ld-framing/issues/37</a><br/>
Rob Sanderson: ivan asks why there isn’t a keyword for all the different options<br/>
Ivan Herman: I realized by reading through the document that certain options appeared as keywords<br/>
… others don’t<br/>
Gregg Kellogg: I think there are if you look at the syntax tokens<br/>
Gregg Kellogg: <a href="https://w3c.github.io/json-ld-framing/#framing-keywords">https://w3c.github.io/json-ld-framing/#framing-keywords</a><br/>
Ivan Herman: not sure I remember reading this<br/>
Gregg Kellogg: we very well may have examples that don’t use all the keywords<br/>
Rob Sanderson: > Initialize flags embed, explicit, and requireAll from object embed flag, explicit inclusion flag, and require all flag in state overriding from any property values for @embed, @explicit, and @requireAll in frame.<br/>
Ivan Herman: yeah the examples in the syntax document were way more extensive<br/>
Dave Longley: was just going to say our implementation has those flags in there (and there may be tests as well… at least i hope so) :)<br/>
Gregg Kellogg: my thought initially was that framing would eventually be incorporated in the API document<br/>
… but we decided to leave it in a sep. doc<br/>
… so there’s a backlog of things that have to happen to the document<br/>
Tim Cole: Does 4.1 include @omit-graph?<br/>
Ivan Herman: clearly, if we add more examples to the document then this should fix it<br/>
Proposed resolution: Close Framing #37, as already fixed (Rob Sanderson)<br/>
Gregg Kellogg: there is an open issue I’m working against<br/>
Rob Sanderson: +1<br/>
Pierre-Antoine Champin: +1<br/>
Gregg Kellogg: no it’s in 4.4.3.3<br/>
Benjamin Young: is it a keyword? or an option for the api?<br/>
Gregg Kellogg: well we have keywords for all the options<br/>
Proposed resolution: Keep #37 open for @omit-graph (Rob Sanderson)<br/>
Simon Steyskal: +1<br/>
Ivan Herman: +1<br/>
Rob Sanderson: +1<br/>
Tim Cole: +1<br/>
Benjamin Young: +1<br/>
Dave Longley: +1 … naming convention appears to be camelCase so @omitDefault<br/>
Gregg Kellogg: +1<br/>
Gregg Kellogg: values can have multiple elements (array) part of the reason why this complicates native json support<br/>
David I. Lehn: +1<br/>
David Newbury: +1<br/>
Resolution #2: Keep #37 open for @omit-graph<br/>
</details>

**Comment by gkellogg** [comment]
I'm not sure `@omitGraph` would be particularly useful, as it is only useful at the very top-level and the algorithm doesn't consider it as a possible default when processing a frame object.

Note that it defaults to `true` in 1.1, which is probably what most people want. Adding it to the frame is kind of odd, though.

**Comment by iherman** [comment]
Probably true. But I guess it would require more explanation to describe why this (or other) API flag does _not_ have a keyword equivalent or not. Furthermore, by using this keyword (and others) the creator of a frame ensures that this statement is always there, regardless of how a particular JSON-LD processor is invoked, ie, how the API flags are set...

**Comment by gkellogg** [comment]
See #41, which would remove `@omitDefault` while possibly keeping the flag.

In the case of the omit graph flag, it is never encountered when processing a frame, and it would require something extra to reach into the frame to see if this had been set. The default in 1.1 is to omit it, and the flag mostly exists to be able to explicitly go back to the 1.0 behavior.

**Comment by azaroth42** [comment]
So we can close?

**Comment by azaroth42** [comment]
Closed by resolution: https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-03-29-json-ld#resolution4

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-03-29-json-ld#section4-5).

- `RESOLVED:  Close #37, only edge edge cases when there is disparity`
<details><summary><i class="differentiate">View the transcript</i></summary>
4.5. Keywords / Flags<br/>
Ivan Herman: link: <a href="https://github.com/w3c/json-ld-framing/issues/37">https://github.com/w3c/json-ld-framing/issues/37</a><br/>
Rob Sanderson: would we have complete parity between keywords and flags?<br/>
Proposed resolution: Close #37, only edge cases when there is disparity (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Ivan Herman: we have the parity for most of them;<br/>
Ivan Herman: +1<br/>
Dave Longley: +1<br/>
Ruben Taelman: +1<br/>
Gregg Kellogg: +1<br/>
Tim Cole: +1<br/>
Ivan Herman: those were we don’t are edge cases, so I’m fine with closing it<br/>
Pierre-Antoine Champin: +1<br/>
David Newbury: +1<br/>
David I. Lehn: +1<br/>
Resolution #4: Close #37, only edge edge cases when there is disparity<br/>
Adam Soroka: +1<br/>
</details>
