### ISSUE TITLE
infinite recursion in @reverse properties

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-framing#5]
From json-ld/json-ld.org#653

It would be nice to have the same possiblity of infinite recursion in the `@reverse` properties as there are in non-reverse ones ([example](https://json-ld.org/playground-dev/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22prefLabel%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23prefLabel%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxHasSubClass%22%3A%5B%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0001%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0010%22%7D%5D%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0001%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxHasSubClass%22%3A%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0002%22%7D%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0002%22%2C%22%40type%22%3A%22Taxonomy%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0010%22%2C%22%40type%22%3A%22Taxonomy%22%7D%5D%7D&frame=%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605%22%2C%22%40context%22%3A%7B%22children%22%3A%7B%22%40reverse%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%7D%2C%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%7D&context=%7B%22%40context%22%3A%7B%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22prefLabel%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23prefLabel%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%7D)), currently recursion only works as many times as the frame defines it ([example](https://json-ld.org/playground-dev/#startTab=tab-framed&json-ld=%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605%22%2C%22%40type%22%3A%22Taxonomy%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0001%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxSubclassOf%22%3A%22bdr%3AO9TAXTBRC201605%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0002%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxSubclassOf%22%3A%22bdr%3AO9TAXTBRC201605_0001%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0010%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxSubclassOf%22%3A%22bdr%3AO9TAXTBRC201605%22%7D%5D%2C%22%40context%22%3A%7B%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%7D&frame=%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605%22%2C%22%40context%22%3A%7B%22children%22%3A%7B%22%40reverse%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%7D%2C%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%2C%22children%22%3A%7B%7D%7D)).

Copy/pasting the examples (and removing `@context`s):

in the working case, I have

```json
{
  "@graph": [
    {
      "@id": "bdr:O9TAXTBRC201605",
      "@type": "Taxonomy",
      "taxHasSubClass": [
        {
          "@id": "bdr:O9TAXTBRC201605_0001"
        },
        {
          "@id": "bdr:O9TAXTBRC201605_0010"
        }
      ]
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0001",
      "@type": "Taxonomy",
      "taxHasSubClass": {
        "@id": "bdr:O9TAXTBRC201605_0002"
      }
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0002",
      "@type": "Taxonomy"
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0010",
      "@type": "Taxonomy"
    }
  ]
}
```

and frame

```json
{ 
  "@id" : "bdr:O9TAXTBRC201605",
  "@context" : {
    "children": { "@reverse": "http://purl.bdrc.io/ontology/core/taxSubclassOf" }, 
    "taxSubclassOf" : {
      "@id" : "http://purl.bdrc.io/ontology/core/taxSubclassOf",
      "@type" : "@id"
    },
    "@vocab" : "http://purl.bdrc.io/ontology/core/",
    "bdr" : "http://purl.bdrc.io/resource/"
  }
}
```

that produces the nice

```json
{
  "@graph": [
    {
      "@id": "bdr:O9TAXTBRC201605",
      "@type": "Taxonomy",
      "taxHasSubClass": [
        {
          "@id": "bdr:O9TAXTBRC201605_0001",
          "@type": "Taxonomy",
          "taxHasSubClass": {
            "@id": "bdr:O9TAXTBRC201605_0002",
            "@type": "Taxonomy"
          }
        },
        {
          "@id": "bdr:O9TAXTBRC201605_0010",
          "@type": "Taxonomy"
        }
      ]
    }
  ]
}
```

but for the opposite:

```json
{
  "@graph": [
    {
      "@id": "bdr:O9TAXTBRC201605",
      "@type": "Taxonomy"
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0001",
      "@type": "Taxonomy",
      "taxSubclassOf": "bdr:O9TAXTBRC201605"
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0002",
      "@type": "Taxonomy",
      "taxSubclassOf": "bdr:O9TAXTBRC201605_0001"
    },
    {
      "@id": "bdr:O9TAXTBRC201605_0010",
      "@type": "Taxonomy",
      "taxSubclassOf": "bdr:O9TAXTBRC201605"
    }
  ]
}
```

and the frame

```json
{
  "@id": "bdr:O9TAXTBRC201605",
  "@context": {
    "children": {
      "@reverse": "http://purl.bdrc.io/ontology/core/taxSubclassOf"
    },
    "taxSubclassOf": {
      "@id": "http://purl.bdrc.io/ontology/core/taxSubclassOf",
      "@type": "@id"
    },
    "@vocab": "http://purl.bdrc.io/ontology/core/",
    "bdr": "http://purl.bdrc.io/resource/"
  },
  "children": {}
}
```

I'm not getting all the recursion, only

```json
{
  "@graph": [
    {
      "@id": "bdr:O9TAXTBRC201605",
      "children": [
        {
          "@id": "bdr:O9TAXTBRC201605_0001",
          "@type": "Taxonomy",
          "taxSubclassOf": "bdr:O9TAXTBRC201605"
        },
        {
          "@id": "bdr:O9TAXTBRC201605_0010",
          "@type": "Taxonomy",
          "taxSubclassOf": "bdr:O9TAXTBRC201605"
        }
      ],
      "@type": "Taxonomy"
    }
  ]
}
```

**Comment by azaroth42** [comment]
:+1: to the use case. Have you tried implementing a solution to this, @gkellogg ?

**Comment by gkellogg** [comment]
I generally implement things before considering a specification update, and I'll take a look, in due course. (Unless, of course @dlongley or @davidlehn beat me to it!).

**Comment by azaroth42** [comment]
[Resolution on the WG call](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-09-14-json-ld#resolution4) of 2018-09-14 was to accept this issue as valid and valuable, and to seek additional implementation experience for potential solutions.

**Comment by gkellogg** [comment]
So, this ends up running afoul of the general framing algorithm. When framing a property with a node value, it looks for a frame associated with the property, if there is none, it constructs one using `@embed`, `@explicit` and `@requireAll`:

From Framing 4.4.2.3.2:

> ... If _frame_ does not exist, create a new frame using a new dictionary with properties for `@embed`, `@explicit` and `@requireAll` taken from _embed_, _explicit_ and _requireAll_.

The requested logic would require us to construct a new frame based on properties of the existing frame, which could have wide implications.

The best we can do without radical changes would be to make the sub-frames explicit ([playground](https://json-ld.org/playground-dev/#startTab=tab-framed&json-ld=%7B%22%40graph%22%3A%5B%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605%22%2C%22%40type%22%3A%22Taxonomy%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0001%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxSubclassOf%22%3A%22bdr%3AO9TAXTBRC201605%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0002%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxSubclassOf%22%3A%22bdr%3AO9TAXTBRC201605_0001%22%7D%2C%7B%22%40id%22%3A%22bdr%3AO9TAXTBRC201605_0010%22%2C%22%40type%22%3A%22Taxonomy%22%2C%22taxSubclassOf%22%3A%22bdr%3AO9TAXTBRC201605%22%7D%5D%2C%22%40context%22%3A%7B%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%7D%7D&frame=%7B%22%40context%22%3A%7B%22%40vocab%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2F%22%2C%22taxSubclassOf%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22bdr%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fresource%2F%22%2C%22children%22%3A%7B%22%40reverse%22%3A%22http%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fcore%2FtaxSubclassOf%22%7D%7D%2C%22%40id%22%3A%22bdr%3AO9TAXTBRC201605%22%2C%22children%22%3A%7B%22children%22%3A%7B%22children%22%3A%7B%7D%7D%7D%7D)):

```json
{ 
  "@context" : {
    "@vocab" : "http://purl.bdrc.io/ontology/core/",
    "taxSubclassOf" : {
      "@id" : "http://purl.bdrc.io/ontology/core/taxSubclassOf",
      "@type" : "@id"
    },
    "bdr" : "http://purl.bdrc.io/resource/",
    "children": { "@reverse": "http://purl.bdrc.io/ontology/core/taxSubclassOf" }
  },
  "@id" : "bdr:O9TAXTBRC201605",
  "children": {
    "children": {
      "children": {}
    }
  }
}
```

This generates the following, with backwards and forwards links:

```json
{
  "@context" : {
    "@vocab" : "http://purl.bdrc.io/ontology/core/",
    "taxSubclassOf" : {
      "@id" : "http://purl.bdrc.io/ontology/core/taxSubclassOf",
      "@type" : "@id"
    },
    "bdr" : "http://purl.bdrc.io/resource/",
    "children": { "@reverse": "http://purl.bdrc.io/ontology/core/taxSubclassOf" }
  },
  "@id" : "bdr:O9TAXTBRC201605",
  "children": [{
    "@id": "bdr:O9TAXTBRC201605_0001",
    "@type": "Taxonomy",
    "taxSubclassOf": "bdr:O9TAXTBRC201605",
    "children": {
      "@id": "bdr:O9TAXTBRC201605_0002",
      "@type": "Taxonomy",
      "taxSubclassOf": "bdr:O9TAXTBRC201605_0001"
    }
  }, {
    "@id": "bdr:O9TAXTBRC201605_0010",
    "@type": "Taxonomy",
    "taxSubclassOf": "bdr:O9TAXTBRC201605"
  }]
}
```

(Note that unused repetitions of "children" are ignored if there are no children).

This seems like an acceptable solution to me requiring no change.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-05-json-ld#section3-1).

- `RESOLVED:  Add a note to the framing spec about the asymmetry, and longer explanation with examples in the primer document for issue framing#5 on @reverse recursion`
<details><summary><i class="differentiate">View the transcript</i></summary>
3.1. Infinite @reverse framing recursion (Gregg’s findings)<br/>
Rob Sanderson: link: <a href="https://github.com/w3c/json-ld-framing/issues/5">https://github.com/w3c/json-ld-framing/issues/5</a><br/>
Gregg Kellogg: raises question about framing design criteria<br/>
… if there is no frame to be matched, algo constructs one<br/>
… so if you have something that infinitely recurses on @reverse, would mean a change to algo<br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-framing/issues/5#issuecomment-426846317">https://github.com/w3c/json-ld-framing/issues/5#issuecomment-426846317</a><br/>
Gregg Kellogg: solution suggested in my latest comment is to use frame as really intended<br/>
… you would create necessary children finitely<br/>
Rob Sanderson: does this mean it works any differently for @reverse?<br/>
Gregg Kellogg: not really. In the absence of a property in the reverse it would create it.<br/>
Rob Sanderson: so if wanted to be explicit in the non-reverse direction you would just ???<br/>
Gregg Kellogg: no change, but describe behavior / example in primer<br/>
Rob Sanderson: questions?<br/>
Rob Sanderson: s/???/include them explicitly in the frame, the same as for @reverse/<br/>
Rob Sanderson: if not, how do we want to resolve? example in spec or note in primer?<br/>
Benjamin Young: willing to take a crack at what should go into primer<br/>
Adam Soroka: agree<br/>
Rob Sanderson: a note in the spec and then a longer discussion in primer?<br/>
Proposed resolution: Add a note to the framing spec about the asymmetry, and longer explanation with examples in the primer document for issue framing#5 on @reverse recursion (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Benjamin Young: +1<br/>
Ivan Herman: +1<br/>
Tim Cole: +1<br/>
Adam Soroka: +1<br/>
Simon Steyskal: +1<br/>
Jeff Mixter: +1<br/>
Rob Sanderson: +1<br/>
Benjamin Young: +1<br/>
Resolution #2: Add a note to the framing spec about the asymmetry, and longer explanation with examples in the primer document for issue framing#5 on @reverse recursion<br/>
</details>
