### ISSUE TITLE
Or ... can `@graph` be used in a frame document to dictate the presence of `@graph` in the resulting JSON-LD document?

### ISSUE THREAD

**Issue by nicholasmcclain65** [w3c/json-ld-framing#56]
Or ... can `@graph` be used in a frame document to dictate the presence of `@graph` in the resulting JSON-LD document?

_Originally posted by @azaroth42 in https://github.com/w3c/json-ld-framing/issues/38#issuecomment-463378513_

**Comment by gkellogg** [comment]
Yes, frames can include `@graph` to include named graphs in addition to either the merge or default graph. See [Framing Named Graphs](https://w3c.github.io/json-ld-framing/#framing-named-graphs).

**Comment by azaroth42** [comment]
Closing, no issue :)
