### ISSUE TITLE
Frame Matching & Blank Nodes

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-framing#9]
The current draft for JSON-LD framing (January 2018) does not mention blank nodes in the [frame matching algorithm specification](https://json-ld.org/spec/latest/json-ld-framing/#frame-matching) and a strict interpretation of the first test goes a bit against the semantics of RDF in case a frame includes blank nodes:

> __1__ Node matches if it has an `@id` property value which is also a value of the `@id` property in frame.

According to its definition, a frame is a JSON-LD document, meaning it can include blank nodes. if it happens, blank nodes in the frame will match blank nodes in a document only if they have the same ID and I believe that the [Ruby implementation](https://github.com/ruby-rdf/json-ld/blob/develop/lib/json/ld/frame.rb#L293) performs simple string comparison.

In RDF, shared blank nodes require a [special handling](https://www.w3.org/TR/rdf11-mt/#shared-blank-nodes-unions-and-merges) and we loose that specificity here. It would be good to either redefine JSON-LD frames such that blank nodes are not allowed or precise the specification of frame matching. I would be in favor of the latter approach.

Blank nodes in JSON-LD frames might be useful when nodes have multiple relations to each other. For instance, nodes matching the following frame represent all alumni of a university who still work for that university:

```js
{
  "@context": "http://schema.org",
  "@type": "Person",
  "alumniOf": {
    "@id": "_:univ",
    "@type": "CollegeOrUniversity"
  },
  "worksFor": { "@id": "_:univ" }
}
```

Original issue json-ld/json-ld.org#579.

**Comment by elf-pavlik** [comment]
> Blank nodes in JSON-LD frames might be useful when nodes have multiple relations to each other. For instance, nodes matching the following frame represent all alumni of a university who still work for that university

I think N3 and SPARQL would use variables in such cases `?univ`
